image: Visual Studio 2022

install:
  - ps: |
      $logo = (Invoke-WebRequest "https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.raw").toString()
      Write-Host "$logo" -ForegroundColor Green

before_build:
  - nuget restore